import '../app/globals.css'; // Global styles
import type { Metadata } from 'next';
import MainLayout from '@/Components/MainLayout'; // Absolute import (works if configured in tsconfig)

export const metadata: Metadata = {
  title: 'My Ant Design App',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}